#!/bin/bash
#
#
echo "Sisesta präeguse kuu number"
read kuu
if test $kuu -eq 1 -o $kuu -eq 12 -o $kuu -eq 12
then
	echo "On talv"
elif test $kuu -ge 3 -a $kuu -le 5
then
	echo "Präegu on kevad"
elif test $kuu -ge 6 -a $kuu -le 8
then
	echo "On suvi"
elif test $kuu -ge 9 -a $kuu -le 11
then
	echo "On sügis"
else 
	echo "Sellist kuud pole olemas"
fi

#
#
#
#
