#!/bin/bash
# tervitusskript
#
echo -n "Tere, " # väljasta ilma reavahetuseta Tere,
echo -n "${USER}" # väljasta ilma reavahetuseta präeguse kasutaja nime
echo "!" # väljasta ! ja tee reavahetus
#
# skripti lõpp
