#!/bin/bash
#
#Kokkamise skript
echo "Sisestage soovitud tordi pikkus"
read pikkus
echo "Sisestage soovitud tordi laius"
read laius
echo "Sisestage kui palju kihte tordil on"
read kihid
echo "Sisestage küpsise pikkus"
read kyppikkus
echo "Sisestage küpsise laius"
read kyplaius
echo "Sisestage kui palju küpsiseid ühes pakis on"
read pakk
kyppindala=`expr $kyppikkus \* $kyplaius`
pindala=`expr $pikkus \* $laius` 
kypsistearv=`expr $pindala / $kyppindala`
kook=`expr $pindala \* $kihid`
kyp=`expr $kypsistearv \* $kihid`
pakkis=`expr $kyp / $pakk`
j22k=`expr $kypsistearv % $pakk`
echo "Vaja läheb $kyp pakki ja $j22k küpsist"

 

#
#
#

